import java.io.FileOutputStream;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import java.util.Date;/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class billing extends javax.swing.JFrame {
public int finalTotal=0;
    /**
     * Creates new form billing
     */ResultSet rs;
    public billing() {
        initComponents();
        setBounds(1,1,1354, 779);
        SimpleDateFormat dformat=new SimpleDateFormat("dd-MM-yyyy");
        Date date=new Date();
        jLabel20.setText(dformat.format(date));
        
        DateTimeFormatter dtf=DateTimeFormatter.ofPattern("HH:mm:ss");
        LocalDateTime now=LocalDateTime.now();
        jLabel21.setText(dtf.format(now));
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        t4 = new javax.swing.JTextField();
        t1 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        t6 = new javax.swing.JTextField();
        t10 = new javax.swing.JTextField();
        t8 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt1 = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        t12 = new javax.swing.JTextField();
        t9 = new javax.swing.JTextField();
        b1 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        t11 = new javax.swing.JTextField();
        t7 = new javax.swing.JTextField();
        t5 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        t13 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        t14 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jLabel1.setText("Billing");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(180, 20, 170, 90);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screenshot (67).png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 30, 100, 80);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 132, 1360, 10);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Time:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(870, 60, 70, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Date:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(870, 20, 70, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Calculation Details:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(630, 450, 240, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Contact NO");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(300, 190, 120, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Email");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(680, 190, 120, 40);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Address");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(1000, 190, 120, 40);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Product Id");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 310, 120, 40);

        t4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(t4);
        t4.setBounds(1090, 190, 220, 40);

        t1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        getContentPane().add(t1);
        t1.setBounds(80, 190, 200, 40);

        t3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(t3);
        t3.setBounds(760, 190, 220, 40);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(0, 252, 1350, 10);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText("Buyers Details:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(10, 140, 200, 40);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Product Name");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(210, 310, 130, 40);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Rate");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(580, 310, 50, 40);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Total");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(640, 510, 100, 40);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Name");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(10, 190, 120, 40);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("Quantity");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(780, 310, 90, 40);

        t6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(t6);
        t6.setBounds(350, 310, 220, 40);

        t10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(t10);
        t10.setBounds(830, 510, 200, 40);

        t8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        t8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t8ActionPerformed(evt);
            }
        });
        getContentPane().add(t8);
        t8.setBounds(870, 310, 140, 40);

        t2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        t2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2ActionPerformed(evt);
            }
        });
        getContentPane().add(t2);
        t2.setBounds(430, 190, 220, 40);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(0, 422, 1360, 10);

        jt1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Description", "Rate", "Quantity", "Total"
            }
        ));
        jScrollPane1.setViewportView(jt1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 440, 600, 320);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel16.setText("Product Details:");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(10, 260, 200, 40);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("Total Amount");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(640, 610, 130, 40);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setText("Discription");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(1030, 310, 100, 40);

        t12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(t12);
        t12.setBounds(830, 610, 200, 40);

        t9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(t9);
        t9.setBounds(1140, 310, 200, 40);

        b1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screenshot (81).png"))); // NOI18N
        b1.setText("ADD");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        getContentPane().add(b1);
        b1.setBounds(1000, 370, 150, 40);

        b5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        b5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screenshot (73).png"))); // NOI18N
        b5.setText("Close");
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });
        getContentPane().add(b5);
        b5.setBounds(1150, 570, 140, 40);

        b3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        b3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screenshot (75).png"))); // NOI18N
        b3.setText("Save");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        getContentPane().add(b3);
        b3.setBounds(1150, 510, 140, 40);

        b2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screenshot (80).png"))); // NOI18N
        b2.setText("DELETE");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        getContentPane().add(b2);
        b2.setBounds(1160, 370, 150, 40);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setText("Discount");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(640, 560, 120, 40);

        t11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(t11);
        t11.setBounds(830, 560, 200, 40);

        t7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(t7);
        t7.setBounds(650, 310, 110, 40);

        t5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(t5);
        t5.setBounds(120, 310, 70, 40);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setText("jLabel21");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(960, 60, 150, 30);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setText("jLabel20");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(960, 20, 150, 30);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setText("Return Amount");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(640, 710, 140, 40);

        t13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        t13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t13ActionPerformed(evt);
            }
        });
        getContentPane().add(t13);
        t13.setBounds(830, 660, 200, 40);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel23.setText("Paid Amount");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(640, 660, 120, 40);

        t14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(t14);
        t14.setBounds(830, 710, 200, 40);

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screenshot (82).png"))); // NOI18N
        jLabel24.setText("jLabel24");
        getContentPane().add(jLabel24);
        jLabel24.setBounds(0, 0, 1360, 780);

        jButton1.setText("jButton1");
        getContentPane().add(jButton1);
        jButton1.setBounds(1240, 590, 79, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t8ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_b5ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
    
String path="D:\\";
com.itextpdf.text.Document doc=new com.itextpdf.text.Document();// TODO add your handling code here:
try
{
    PdfWriter.getInstance(doc, new FileOutputStream(path+""+t1.getText()+" "+jLabel20.getText()+"pdf"));
doc.open();
Paragraph paragraph1=new Paragraph("Muskan(project)\n      Contact Number:(+91)1234567890\n\n");
doc.add(paragraph1);
Paragraph paragraph2=new Paragraph("Date & Time:"+jLabel20.getText()+" "+jLabel21.getText()+"\nBuyer Details:\nName:"+t1.getText()+"\nContact:"+t2.getText()+"\nEmail:"+t3.getText()+"\nAddress:"+t4.getText()+"\n\n");
doc.add(paragraph2); 
PdfPTable tb1=new PdfPTable(5);
tb1.addCell("Name");
tb1.addCell("Description");
tb1.addCell("Rate");
tb1.addCell("Quantity");
tb1.addCell("Total");
for(int i=0;i<jt1.getRowCount();i++)
{
    String n=jt1.getValueAt(1,0).toString();
    String d=jt1.getValueAt(1,1).toString();
    String r=jt1.getValueAt(1,2).toString();
    String q=jt1.getValueAt(1,3).toString();
    String t=jt1.getValueAt(1,4).toString();
    tb1.addCell(n);
    tb1.addCell(d);
    tb1.addCell(r);
    tb1.addCell(q);
    tb1.addCell(t);
}
doc.add(tb1);
Paragraph paragraph3=new Paragraph("\nTotal"+t10.getText()+"\nDiscount"+t11.getText()+"\nTotal Amount"+t12.getText()+"\nPaid Amount"+t13.getText()+"\nReturn Amount"+t14.getText());
doc.add(Paragraph3);
JOptionPane.showMessageDialog(null,"Bill generated");
        }
catch(Exception e)
{}
doc.close();
    }//GEN-LAST:event_b3ActionPerformed

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
String Name=t1.getText();
try
{
    Class.forName("com.mysql.jdbc.Driver");
        Connection c=DriverManager.getConnection("jdbc:mysql://localhost:3307/project","root","");
       Statement st=c.createStatement();
       ResultSet rs=st.executeQuery("select * from newbuyer where Name like='"+Name+"'");
       if(rs.next())
       {
           t1.setText(rs.getString(1));
           t2.setText(rs.getString(2));
           t3.setText(rs.getString(3));
           t4.setText(rs.getString(4));
       }
       else
       {   t2.setText("");
       t3.setText("");
       t4.setText("");
       }
}
catch(Exception e)
{
    
}// TODO add your handling code here:
    }//GEN-LAST:event_t1ActionPerformed

    private void t2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2ActionPerformed
String ContactNo=t2.getText();
try
{
    Class.forName("com.mysql.jdbc.Driver");
        Connection c=DriverManager.getConnection("jdbc:mysql://localhost:3307/project","root","");
       Statement st=c.createStatement();
       ResultSet rs=st.executeQuery("select * from newbuyer where ContactNo like='"+ContactNo+"'");
       if(rs.next())
       {
           t1.setText(rs.getString(1));
           t2.setText(rs.getString(2));
           t3.setText(rs.getString(3));
           t4.setText(rs.getString(4));
       }
       else
       {   t1.setText("");
       t3.setText("");
       t4.setText("");
       }
}
catch(Exception e)
{
    
}        // TODO add your handling code here:
    }//GEN-LAST:event_t2ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
int price=Integer.parseInt(t7.getText());
int quantity=Integer.parseInt(t8.getText());
int total=price*quantity;        
        DefaultTableModel model=(DefaultTableModel)jt1.getModel();
model.addRow(new Object[]{t6.getText(),t9.getText(),price,quantity,total});
finalTotal=finalTotal+total;
String finalTotal1=String.valueOf(finalTotal);
t10.setText(finalTotal1);
// TODO add your handling code here:
    }//GEN-LAST:event_b1ActionPerformed

    private void t13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t13ActionPerformed
String paidAmount=t13.getText();
int z=Integer.parseInt(paidAmount);
finalTotal=z-finalTotal;
String finalTotal1=String.valueOf(finalTotal);
t14.setText(finalTotal1);
t14.setEditable(false);

// TODO add your handling code here:
    }//GEN-LAST:event_t13ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
DefaultTableModel model=(DefaultTableModel)jt1.getModel();
try
{
 int SelectedRowIndex=jt1.getSelectedRow();
 model.removeRow(SelectedRowIndex);
}
catch(Exception e)
{
}
t1.setText(" ");
t2.setText(" ");
t3.setText(" ");
t4.setText(" ");
t5.setText(" ");
t6.setText(" ");
t7.setText(" ");
t8.setText(" ");
t9.setText(" ");
t10.setText(" ");
// TODO add your handling code here:
    }//GEN-LAST:event_b2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new billing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b5;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jt1;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t10;
    private javax.swing.JTextField t11;
    private javax.swing.JTextField t12;
    private javax.swing.JTextField t13;
    private javax.swing.JTextField t14;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    private javax.swing.JTextField t7;
    private javax.swing.JTextField t8;
    private javax.swing.JTextField t9;
    // End of variables declaration//GEN-END:variables
}
