/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HP
 */import javax.swing.JOptionPane;
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
        this.setBounds(1,1,2000,1200);
        b2.setVisible(false);
        b3.setVisible(false);
        b4.setVisible(false);
        b5.setVisible(false);
        b6.setVisible(false);
        b7.setVisible(false);
        b8.setVisible(false);
        b9.setVisible(false);
        b10.setVisible(false);
        b11.setVisible(false);
        b12.setVisible(false);
        l2.setVisible(false);
        l3.setVisible(false);
        l4.setVisible(false);
        l5.setVisible(false);
        l6.setVisible(false);
        l7.setVisible(false);
        l8.setVisible(false);
        l9.setVisible(false);
        l10.setVisible(false);
        l11.setVisible(false);
        l12.setVisible(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b3 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        b10 = new javax.swing.JButton();
        b12 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        l11 = new javax.swing.JLabel();
        l10 = new javax.swing.JLabel();
        l9 = new javax.swing.JLabel();
        l8 = new javax.swing.JLabel();
        l7 = new javax.swing.JLabel();
        l6 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        l12 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        l5 = new javax.swing.JLabel();
        b2 = new javax.swing.JButton();
        b11 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        b3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screenshot (60).png"))); // NOI18N
        b3.setText("jButton1");
        b3.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                b3ComponentShown(evt);
            }
        });
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        getContentPane().add(b3);
        b3.setBounds(270, 30, 100, 80);

        b5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screenshot (62).png"))); // NOI18N
        b5.setText("jButton1");
        b5.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                b5ComponentShown(evt);
            }
        });
        getContentPane().add(b5);
        b5.setBounds(600, 30, 110, 80);

        b4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screenshot (61).png"))); // NOI18N
        b4.setText("jButton1");
        b4.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                b4ComponentShown(evt);
            }
        });
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });
        getContentPane().add(b4);
        b4.setBounds(430, 30, 100, 80);

        b6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screenshot (63).png"))); // NOI18N
        b6.setText("jButton1");
        b6.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                b6ComponentShown(evt);
            }
        });
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });
        getContentPane().add(b6);
        b6.setBounds(770, 30, 110, 80);

        b8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screenshot (65).png"))); // NOI18N
        b8.setText("jButton1");
        b8.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                b8ComponentShown(evt);
            }
        });
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });
        getContentPane().add(b8);
        b8.setBounds(1110, 30, 100, 80);

        b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screenshot (58).png"))); // NOI18N
        b1.setText("jButton1");
        b1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b1MouseClicked(evt);
            }
        });
        getContentPane().add(b1);
        b1.setBounds(10, 30, 90, 80);

        b9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screenshot (66).png"))); // NOI18N
        b9.setText("jButton1");
        b9.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                b9ComponentShown(evt);
            }
        });
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });
        getContentPane().add(b9);
        b9.setBounds(1280, 30, 100, 80);

        b10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screenshot (67).png"))); // NOI18N
        b10.setText("jButton1");
        b10.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                b10ComponentShown(evt);
            }
        });
        b10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b10ActionPerformed(evt);
            }
        });
        getContentPane().add(b10);
        b10.setBounds(1440, 30, 100, 80);

        b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screenshot (69).png"))); // NOI18N
        b12.setText("jButton1");
        b12.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                b12ComponentShown(evt);
            }
        });
        b12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b12ActionPerformed(evt);
            }
        });
        getContentPane().add(b12);
        b12.setBounds(1740, 30, 100, 80);

        b7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screenshot (64).png"))); // NOI18N
        b7.setText("jButton1");
        b7.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                b7ComponentShown(evt);
            }
        });
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });
        getContentPane().add(b7);
        b7.setBounds(950, 30, 100, 80);

        l11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        l11.setText("Logout");
        getContentPane().add(l11);
        l11.setBounds(1600, 130, 90, 20);

        l10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        l10.setText("Billing");
        getContentPane().add(l10);
        l10.setBounds(1450, 130, 100, 20);

        l9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        l9.setText("Delete Product");
        getContentPane().add(l9);
        l9.setBounds(1270, 130, 140, 20);

        l8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        l8.setText("Product Details");
        getContentPane().add(l8);
        l8.setBounds(1100, 130, 140, 20);

        l7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        l7.setText("Update Product");
        getContentPane().add(l7);
        l7.setBounds(930, 130, 140, 20);

        l6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        l6.setText("New Product");
        getContentPane().add(l6);
        l6.setBounds(770, 130, 117, 20);

        l4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        l4.setText("Buyer Details");
        getContentPane().add(l4);
        l4.setBounds(430, 130, 153, 20);

        l12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        l12.setText("Close Application");
        getContentPane().add(l12);
        l12.setBounds(1710, 130, 153, 22);

        l3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        l3.setText("Update Buyer");
        getContentPane().add(l3);
        l3.setBounds(260, 130, 122, 20);

        l2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        l2.setText("New Buyer");
        getContentPane().add(l2);
        l2.setBounds(130, 130, 110, 22);

        l5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        l5.setText("Delete Buyer");
        getContentPane().add(l5);
        l5.setBounds(600, 130, 117, 20);

        b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screenshot (59).png"))); // NOI18N
        b2.setText("jButton1");
        b2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                b2ComponentShown(evt);
            }
        });
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        getContentPane().add(b2);
        b2.setBounds(130, 30, 90, 80);

        b11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screenshot (68).png"))); // NOI18N
        b11.setText("jButton1");
        b11.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                b11ComponentShown(evt);
            }
        });
        b11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b11ActionPerformed(evt);
            }
        });
        getContentPane().add(b11);
        b11.setBounds(1590, 30, 90, 80);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screenshot (71).png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1890, 1050);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b12ActionPerformed
int a=JOptionPane.showConfirmDialog(null, "Do you really want to close the application","Select",JOptionPane.YES_NO_OPTION);
if(a==0)
{
    System.exit(0);
}// TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_b12ActionPerformed

    private void b11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b11ActionPerformed
int a=JOptionPane.showConfirmDialog(null, "Do you really want to close the application","Select",JOptionPane.YES_NO_OPTION);
if(a==0)
{
    setVisible(false);
    login li=new login();
    li.setVisible(true);
}     // TODO add your handling code here:
    }//GEN-LAST:event_b11ActionPerformed

    private void b2ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_b2ComponentShown
     try
      {
        Thread.sleep(250);
        b3.setVisible(true);
        l3.setVisible(true);
       
      }
      catch(Exception e)
      {}    // TODO add your handling code here:
    }//GEN-LAST:event_b2ComponentShown

    private void b3ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_b3ComponentShown
       try
      {
        Thread.sleep(250);
        b4.setVisible(true);
        l4.setVisible(true);
       
      }
      catch(Exception e)
      {}  // TODO add your handling code here:
    }//GEN-LAST:event_b3ComponentShown

    private void b4ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_b4ComponentShown
      try
      {
        Thread.sleep(250);
        b5.setVisible(true);
        l5.setVisible(true);
       
      }
      catch(Exception e)
      {}   // TODO add your handling code here:
    }//GEN-LAST:event_b4ComponentShown

    private void b5ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_b5ComponentShown
       try
      {
        Thread.sleep(250);
        b6.setVisible(true);
        l6.setVisible(true);
       
      }
      catch(Exception e)
      {}  // TODO add your handling code here:
    }//GEN-LAST:event_b5ComponentShown

    private void b6ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_b6ComponentShown
      try
      {
        Thread.sleep(250);
        b7.setVisible(true);
        l7.setVisible(true);
       
      }
      catch(Exception e)
      {}   // TODO add your handling code here:
    }//GEN-LAST:event_b6ComponentShown

    private void b7ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_b7ComponentShown
      try
      {
        Thread.sleep(250);
        b8.setVisible(true);
        l8.setVisible(true);
       
      }
      catch(Exception e)
      {}   // TODO add your handling code here:
    }//GEN-LAST:event_b7ComponentShown

    private void b8ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_b8ComponentShown
     try
      {
        Thread.sleep(250);
        b9.setVisible(true);
        l9.setVisible(true);
       
      }
      catch(Exception e)
      {}    // TODO add your handling code here:
    }//GEN-LAST:event_b8ComponentShown

    private void b9ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_b9ComponentShown
       try
      {
        Thread.sleep(250);
        b10.setVisible(true);
        l10.setVisible(true);
       
      }
      catch(Exception e)
      {}  // TODO add your handling code here:
    }//GEN-LAST:event_b9ComponentShown

    private void b10ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_b10ComponentShown
      try
      {
        Thread.sleep(250);
        b11.setVisible(true);
        l11.setVisible(true);
       
      }
      catch(Exception e)
      {}   // TODO add your handling code here:
    }//GEN-LAST:event_b10ComponentShown

    private void b11ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_b11ComponentShown
        try
      {
        Thread.sleep(250);
        b12.setVisible(true);
        l12.setVisible(true);
       
      }
      catch(Exception e)
      {} // TODO add your handling code here:
    }//GEN-LAST:event_b11ComponentShown

    private void b12ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_b12ComponentShown
         // TODO add your handling code here:
    }//GEN-LAST:event_b12ComponentShown

    private void b1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b1MouseClicked
      try
      {
        Thread.sleep(250);
        b2.setVisible(true);
        l2.setVisible(true);
       
      }
      catch(Exception e)
      {}
        // TODO add your handling code here:
    }//GEN-LAST:event_b1MouseClicked

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
newbuyer nb=new newbuyer();
nb.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
updatebuyer u1=new updatebuyer();
u1.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_b3ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
buyerdetails b1=new buyerdetails();
b1.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_b4ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
newproduct n1=new newproduct();
n1.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_b6ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
updateproduct u1=new updateproduct();
u1.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_b7ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
productdetail p1=new productdetail();
p1.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_b8ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
deleteproduct d1=new deleteproduct();
d1.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_b9ActionPerformed

    private void b10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b10ActionPerformed
billing b1=new billing();
b1.setVisisble(true);// TODO add your handling code here:
    }//GEN-LAST:event_b10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b10;
    private javax.swing.JButton b11;
    private javax.swing.JButton b12;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel l10;
    private javax.swing.JLabel l11;
    private javax.swing.JLabel l12;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel l6;
    private javax.swing.JLabel l7;
    private javax.swing.JLabel l8;
    private javax.swing.JLabel l9;
    // End of variables declaration//GEN-END:variables
}
